"use client";

/**
 * The FLASHING house, modelled on the Gibraltar flashing diagram the
 * owner supplied: centre gable with valleys, chimney with cricket, shed
 * dormer for step/apron/kickout, door head for Z-flashing.
 *
 * GENERATED by docs/roof-house-geometry.py, edit the model there and re-run
 * (then docs/sync-roof-anchors.py). Hand-editing desynchronises the pins.
 *
 * Neutral colours throughout; ember is reserved for the active highlight,
 * applied via CSS (which overrides SVG presentation attributes).
 */

import { cn } from "@/lib/utils";

export const FLASHING_SVG_VIEWBOX = { width: 1040, height: 620 };

export function FlashingHouseSvg({
  activeKey,
  className,
  label,
}: {
  activeKey: string;
  className?: string;
  label?: string;
}) {
  const part = (key: string) => ({
    "data-part": key,
    className: cn(
      "transition-[filter,opacity] duration-300",
      key === activeKey &&
        "[filter:drop-shadow(0_0_10px_rgba(201,112,46,0.85))] [&_circle]:fill-ember-500 [&_ellipse]:fill-ember-500 [&_line]:stroke-ember-500 [&_path]:fill-ember-500 [&_polygon]:fill-ember-500 [&_polygon]:stroke-navy-950 [&_polyline]:stroke-ember-500",
    ),
  });

  return (
    <svg
      viewBox="0 0 1040 620"
      className={cn("block h-auto w-full", className)}
      role="img"
      aria-label={label ?? "Illustration of a house with each type of roof flashing marked in place"}
    >
      <defs><linearGradient id="skyF" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#f8fbfd"/><stop offset="100%" stopColor="#eef3f8"/></linearGradient></defs>
      <rect width="1040" height="620" rx="24" fill="url(#skyF)"/>
      <ellipse cx="603" cy="496" rx="480" ry="75" fill="#0d2c4b" opacity="0.07"/>
      <polygon points="175.9,217.2 864.1,52.0 766.5,134.6 78.3,299.8" fill="#6c7986" stroke="#46525e" strokeWidth="1.6" strokeLinejoin="round"/>
      <polygon points="116.7,473.9 283.1,557.1 283.1,365.1 199.9,211.4 116.7,281.8" fill="#e8edf3" stroke="#46525e" strokeWidth="1.6" strokeLinejoin="round"/>
      <polygon points="283.1,557.1 923.3,403.5 923.3,211.4 283.1,365.1" fill="#ffffff" stroke="#46525e" strokeWidth="1.6" strokeLinejoin="round"/>
      <line x1="283.1" y1="392.5" x2="923.3" y2="238.8" stroke="#d5dde6" strokeWidth="1.1"/>
      <line x1="283.1" y1="419.9" x2="923.3" y2="266.3" stroke="#d5dde6" strokeWidth="1.1"/>
      <line x1="283.1" y1="447.4" x2="923.3" y2="293.7" stroke="#d5dde6" strokeWidth="1.1"/>
      <line x1="283.1" y1="474.8" x2="923.3" y2="321.2" stroke="#d5dde6" strokeWidth="1.1"/>
      <line x1="283.1" y1="502.2" x2="923.3" y2="348.6" stroke="#d5dde6" strokeWidth="1.1"/>
      <line x1="283.1" y1="529.7" x2="923.3" y2="376.0" stroke="#d5dde6" strokeWidth="1.1"/>
      <polygon points="273.5,418.8 961.7,253.6 923.3,232.7 283.1,386.4" fill="#d5dde6" stroke="#46525e" strokeWidth="1.4" strokeLinejoin="round"/>
      <polygon points="273.5,397.4 961.7,232.2 961.7,253.6 273.5,418.8" fill="#ffffff" stroke="#46525e" strokeWidth="1.4" strokeLinejoin="round"/>
      <polygon points="175.9,217.2 864.1,52.0 961.7,232.2 273.5,397.4" fill="#8d9aa8" stroke="#46525e" strokeWidth="1.8" strokeLinejoin="round"/>
      <line x1="186.7" y1="237.2" x2="875.0" y2="72.0" stroke="#6c7986" strokeWidth="1" opacity="0.45"/>
      <line x1="197.6" y1="257.2" x2="885.8" y2="92.1" stroke="#6c7986" strokeWidth="1" opacity="0.45"/>
      <line x1="208.4" y1="277.3" x2="896.7" y2="112.1" stroke="#6c7986" strokeWidth="1" opacity="0.45"/>
      <line x1="219.3" y1="297.3" x2="907.5" y2="132.1" stroke="#6c7986" strokeWidth="1" opacity="0.45"/>
      <line x1="230.1" y1="317.3" x2="918.3" y2="152.1" stroke="#6c7986" strokeWidth="1" opacity="0.45"/>
      <line x1="241.0" y1="337.3" x2="929.2" y2="172.2" stroke="#6c7986" strokeWidth="1" opacity="0.45"/>
      <line x1="251.8" y1="357.4" x2="940.0" y2="192.2" stroke="#6c7986" strokeWidth="1" opacity="0.45"/>
      <line x1="262.7" y1="377.4" x2="950.9" y2="212.2" stroke="#6c7986" strokeWidth="1" opacity="0.45"/>
      <polyline points="175.9,217.2 864.1,52.0" fill="none" stroke="#6c7986" strokeWidth="8" strokeLinecap="round"/>
      <g {...part("drip-edge-flashing")}>
      <polyline points="175.9,217.2 273.5,397.4 529.6,336.0" fill="none" stroke="#b9c4cf" strokeWidth="8" strokeLinejoin="round" strokeLinecap="round"/>
      <polyline points="175.9,217.2 273.5,397.4 529.6,336.0" fill="none" stroke="#46525e" strokeWidth="1.4" strokeLinejoin="round" strokeLinecap="round" opacity="0.5"/>
      </g>
      <g {...part("pipe-flashing")}>
      <polygon points="412.7,265.9 461.7,254.1 482.2,291.9 433.1,303.7" fill="#b9c4cf" stroke="#46525e" strokeWidth="1.5" strokeLinejoin="round"/>
      <ellipse cx="447.4" cy="278.9" rx="12.8" ry="5.9" fill="#5b6773" stroke="#46525e" strokeWidth="1.2"/>
      </g>
      <polygon points="439.4,280.8 455.4,277.0 455.4,234.3 439.4,238.1" fill="#12304d" stroke="#46525e" strokeWidth="1.3" strokeLinejoin="round"/>
      <g {...part("chimney-cricket")}>
      <polygon points="313.0,231.0 307.7,138.8 366.4,218.2" fill="#a7b3bf" stroke="#46525e" strokeWidth="1.5" strokeLinejoin="round"/>
      <polyline points="313.0,231.0 307.7,138.8 366.4,218.2" fill="none" stroke="#b9c4cf" strokeWidth="5" strokeLinejoin="round" strokeLinecap="round"/>
      </g>
      <polygon points="338.6,128.3 392.0,115.5 392.0,265.5 338.6,278.3" fill="#e3d5c8" stroke="#46525e" strokeWidth="1.5" strokeLinejoin="round"/>
      <polygon points="338.6,128.3 313.0,115.5 313.0,231.0 338.6,278.3" fill="#d3c2b2" stroke="#46525e" strokeWidth="1.5" strokeLinejoin="round"/>
      <polygon points="338.6,128.3 313.0,115.5 366.4,102.7 392.0,115.5" fill="#efe6dc" stroke="#46525e" strokeWidth="1.5" strokeLinejoin="round"/>
      <g {...part("counter-flashing")}>
      <polyline points="313.0,231.0 338.6,278.3 392.0,265.5 366.4,218.2" fill="none" stroke="#b9c4cf" strokeWidth="9" strokeLinejoin="round" strokeLinecap="round"/>
      </g>
      <polygon points="517.9,308.7 652.3,375.9 652.3,568.0 517.9,500.8" fill="#e8edf3" stroke="#46525e" strokeWidth="1.6" strokeLinejoin="round"/>
      <polygon points="748.3,270.2 844.4,329.8 844.4,521.9 652.3,568.0 652.3,375.9" fill="#ffffff" stroke="#46525e" strokeWidth="1.6" strokeLinejoin="round"/>
      <polygon points="719.0,434.6 777.7,420.5 777.7,537.9 719.0,552.0" fill="#7d8b99" stroke="#46525e" strokeWidth="1.4" strokeLinejoin="round"/>
      <g {...part("z-flashing")}>
      <polyline points="711.0,430.1 785.7,412.2" fill="none" stroke="#b9c4cf" strokeWidth="7" strokeLinecap="round"/>
      </g>
      <polygon points="552.5,172.3 748.3,270.2 844.4,329.8 709.9,262.6" fill="#8d9aa8" stroke="#46525e" strokeWidth="1.7" strokeLinejoin="round"/>
      <polygon points="552.5,172.3 748.3,270.2 652.3,375.9 517.9,308.7" fill="#a7b3bf" stroke="#46525e" strokeWidth="1.7" strokeLinejoin="round"/>
      <polyline points="552.5,172.3 748.3,270.2" fill="none" stroke="#6c7986" strokeWidth="7" strokeLinecap="round"/>
      <g {...part("valley-flashing")}>
      <polyline points="552.5,172.3 517.9,308.7" fill="none" stroke="#b9c4cf" strokeWidth="9" strokeLinecap="round"/>
      <polyline points="552.5,172.3 709.9,262.6" fill="none" stroke="#b9c4cf" strokeWidth="9" strokeLinecap="round"/>
      </g>
      <polygon points="682.2,113.1 810.2,82.4 864.6,128.3 736.6,159.0" fill="#a7b3bf" stroke="#46525e" strokeWidth="1.6" strokeLinejoin="round"/>
      <polygon points="682.2,113.1 736.6,159.0 736.6,222.8 682.2,122.4" fill="#e8edf3" stroke="#46525e" strokeWidth="1.6" strokeLinejoin="round"/>
      <polygon points="736.6,159.0 864.6,128.3 864.6,192.1 736.6,222.8" fill="#ffffff" stroke="#46525e" strokeWidth="1.6" strokeLinejoin="round"/>
      <polygon points="763.3,174.0 838.0,156.0 838.0,201.4 763.3,219.3" fill="#cfe0ee" stroke="#46525e" strokeWidth="1.3" strokeLinejoin="round"/>
      <g {...part("step-flashing")}>
      <line x1="682.2" y1="122.4" x2="690.3" y2="137.4" stroke="#b9c4cf" strokeWidth="8" strokeLinecap="round"/>
      <line x1="693.1" y1="142.5" x2="701.2" y2="157.5" stroke="#b9c4cf" strokeWidth="8" strokeLinecap="round"/>
      <line x1="704.0" y1="162.6" x2="712.1" y2="177.6" stroke="#b9c4cf" strokeWidth="8" strokeLinecap="round"/>
      <line x1="714.8" y1="182.6" x2="723.0" y2="197.7" stroke="#b9c4cf" strokeWidth="8" strokeLinecap="round"/>
      <line x1="725.7" y1="202.7" x2="733.9" y2="217.8" stroke="#b9c4cf" strokeWidth="8" strokeLinecap="round"/>
      </g>
      <g {...part("apron-flashing")}>
      <polyline points="736.6,222.8 864.6,192.1" fill="none" stroke="#b9c4cf" strokeWidth="8" strokeLinecap="round"/>
      </g>
      <g {...part("kickout-flashing")}>
      <path d="M 736.6 222.8 l -16 11 l 22 9 z" fill="#b9c4cf" stroke="#46525e" strokeWidth="1.6" strokeLinejoin="round"/>
      </g>
    </svg>
  );
}
