"use client";

/**
 * Isometric roof illustration shared by the anatomy diagram and the flashing
 * diagram.
 *
 * GENERATED by docs/roof-house-geometry.py, which projects a 3D house model
 * through a fixed axonometric transform and emits this file together with the
 * hot-spot coordinates in config/roof-anatomy.ts. Editing the paths by hand
 * desynchronises the pins from the artwork — change the script and re-run it.
 *
 * Everything draws in neutral, realistic colours; ember is reserved for the
 * active selection so a highlight actually means something. `part()` tags each
 * labelled group, and the highlight works through CSS (which overrides SVG
 * presentation attributes) rather than by re-rendering paths. A group can
 * answer to more than one key: the chimney skirt is "Flashing" in the anatomy
 * diagram and "Counter Flashing" in the flashing one, and shingles appear both
 * in the field and in the cutaway.
 */

import { cn } from "@/lib/utils";

export const ROOF_SVG_VIEWBOX = { width: 1040, height: 620 };

export function RoofHouseSvg({
  activeKey,
  className,
  label,
}: {
  activeKey: string;
  className?: string;
  label?: string;
}) {
  const part = (...keys: string[]) => ({
    "data-part": keys[0],
    className: cn(
      "transition-[filter,opacity] duration-300",
      keys.includes(activeKey)
        ? "[filter:drop-shadow(0_0_10px_rgba(201,112,46,0.85))] [&_circle]:fill-ember-500 [&_ellipse]:fill-ember-500 [&_line]:stroke-ember-500 [&_polygon]:fill-ember-500 [&_polygon]:stroke-navy-950 [&_polyline]:stroke-ember-500"
        : "opacity-100",
    ),
  });

  return (
    <svg
      viewBox="0 0 1040 620"
      className={cn("block h-auto w-full", className)}
      role="img"
      aria-label={
        label ??
        "Cutaway illustration of a house showing every roof component in place"
      }
    >
      <defs><linearGradient id="skyG" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#f8fbfd"/><stop offset="100%" stopColor="#e9f0f7"/></linearGradient></defs>
      <rect width="1040" height="620" rx="24" fill="url(#skyG)"/>
      <ellipse cx="544" cy="503" rx="459" ry="68" fill="#0d2c4b" opacity="0.07"/>
      <polygon points="146.3,232.7 779.6,80.7 685.3,162.7 52.0,314.7" fill="#6c7986" stroke="#46525e" strokeWidth="1.6" strokeLinejoin="round"/>
      <polygon points="86.8,477.0 249.3,558.2 249.3,379.3 168.0,227.5 86.8,298.1" fill="#e8edf3" stroke="#46525e" strokeWidth="1.6" strokeLinejoin="round"/>
      <polygon points="249.3,558.2 839.1,416.7 839.1,237.8 249.3,379.3" fill="#ffffff" stroke="#46525e" strokeWidth="1.6" strokeLinejoin="round"/>
      <line x1="249.3" y1="404.9" x2="839.1" y2="263.3" stroke="#d5dde6" strokeWidth="1.1"/>
      <line x1="249.3" y1="430.4" x2="839.1" y2="288.9" stroke="#d5dde6" strokeWidth="1.1"/>
      <line x1="249.3" y1="456.0" x2="839.1" y2="314.4" stroke="#d5dde6" strokeWidth="1.1"/>
      <line x1="249.3" y1="481.5" x2="839.1" y2="340.0" stroke="#d5dde6" strokeWidth="1.1"/>
      <line x1="249.3" y1="507.1" x2="839.1" y2="365.5" stroke="#d5dde6" strokeWidth="1.1"/>
      <line x1="249.3" y1="532.7" x2="839.1" y2="391.1" stroke="#d5dde6" strokeWidth="1.1"/>
      <polygon points="316.9,406.6 375.0,392.7 375.0,460.4 316.9,474.3" fill="#cfe0ee" stroke="#46525e" strokeWidth="1.4" strokeLinejoin="round"/>
      <g {...part("z-flashing")}>
      <polyline points="312.1,403.9 379.8,387.6" fill="none" stroke="#b9c4cf" strokeWidth="6" strokeLinecap="round"/></g>
      <g {...part("soffit-fascia")}>
      <polygon points="240.6,429.3 873.9,277.3 839.1,258.1 249.3,399.6" fill="#d5dde6" stroke="#46525e" strokeWidth="1.5" strokeLinejoin="round"/>
      <polygon points="240.6,408.9 873.9,256.9 873.9,277.3 240.6,429.3" fill="#ffffff" stroke="#46525e" strokeWidth="1.6" strokeLinejoin="round"/>
      </g>
      <g {...part("gutters")}>
      <polygon points="240.6,429.3 873.9,277.3 879.7,277.3 246.4,429.3" fill="#b9c4cf" stroke="#46525e" strokeWidth="1.4" strokeLinejoin="round"/>
      <polygon points="246.4,429.3 879.7,277.3 879.7,299.5 246.4,451.5" fill="#e6ecf2" stroke="#46525e" strokeWidth="1.5" strokeLinejoin="round"/>
      <polygon points="294.7,439.9 315.0,435.0 315.0,549.1 294.7,554.0" fill="#e6ecf2" stroke="#46525e" strokeWidth="1.4" strokeLinejoin="round"/>
      </g>
      <g {...part("field-shingles")}>
      <polygon points="146.3,232.7 779.6,80.7 873.9,256.9 240.6,408.9" fill="#8d9aa8" stroke="#46525e" strokeWidth="1.8" strokeLinejoin="round"/></g>
      <line x1="156.8" y1="252.3" x2="790.1" y2="100.3" stroke="#6c7986" strokeWidth="1" opacity="0.45"/>
      <line x1="167.2" y1="271.9" x2="800.6" y2="119.9" stroke="#6c7986" strokeWidth="1" opacity="0.45"/>
      <line x1="177.7" y1="291.5" x2="811.0" y2="139.5" stroke="#6c7986" strokeWidth="1" opacity="0.45"/>
      <line x1="188.2" y1="311.1" x2="821.5" y2="159.1" stroke="#6c7986" strokeWidth="1" opacity="0.45"/>
      <line x1="198.7" y1="330.6" x2="832.0" y2="178.6" stroke="#6c7986" strokeWidth="1" opacity="0.45"/>
      <line x1="209.1" y1="350.2" x2="842.5" y2="198.2" stroke="#6c7986" strokeWidth="1" opacity="0.45"/>
      <line x1="219.6" y1="369.8" x2="853.0" y2="217.8" stroke="#6c7986" strokeWidth="1" opacity="0.45"/>
      <line x1="230.1" y1="389.4" x2="863.4" y2="237.4" stroke="#6c7986" strokeWidth="1" opacity="0.45"/>
      <g {...part("decking")}>
      <polygon points="146.3,232.7 240.6,408.9 240.6,416.7 146.3,240.5" fill="#a8874f" stroke="#a8874f" strokeWidth="1.2"/>
      <polygon points="146.3,232.7 190.4,222.2 284.7,398.4 240.6,408.9" fill="#c9a679" stroke="#a8874f" strokeWidth="1.6" strokeLinejoin="round"/>
      </g>
      <g {...part("underlayment")}>
      <polygon points="190.4,214.4 284.7,390.6 284.7,398.4 190.4,222.2" fill="#3d6688" stroke="#3d6688" strokeWidth="1.2"/>
      <polygon points="190.4,214.4 234.5,203.8 328.8,380.0 284.7,390.6" fill="#4f7ea8" stroke="#3d6688" strokeWidth="1.6" strokeLinejoin="round"/>
      </g>
      <g {...part("ice-water-shield")}>
      <polygon points="234.5,196.1 328.8,372.3 328.8,380.0 234.5,203.8" fill="#08203a" stroke="#08203a" strokeWidth="1.2"/>
      <polygon points="234.5,196.1 278.6,185.5 372.9,361.7 328.8,372.3" fill="#12304d" stroke="#08203a" strokeWidth="1.6" strokeLinejoin="round"/>
      </g>
      <g {...part("field-shingles")}>
      <polygon points="278.6,177.8 372.9,354.0 372.9,361.7 278.6,185.5" fill="#6c7986" stroke="#6c7986" strokeWidth="1.2"/>
      <polygon points="278.6,177.8 322.7,167.2 417.0,343.4 372.9,354.0" fill="#a7b3bf" stroke="#6c7986" strokeWidth="1.6" strokeLinejoin="round"/>
      </g>
      <polygon points="405.9,213.3 401.8,102.6 476.0,196.4" fill="#a7b3bf" stroke="#46525e" strokeWidth="1.4" strokeLinejoin="round"/>
      <polygon points="429.1,105.2 499.2,88.4 499.2,239.8 429.1,256.6" fill="#e3d5c8" stroke="#46525e" strokeWidth="1.5" strokeLinejoin="round"/>
      <polygon points="429.1,105.2 405.9,93.6 405.9,213.3 429.1,256.6" fill="#d3c2b2" stroke="#46525e" strokeWidth="1.5" strokeLinejoin="round"/>
      <polygon points="429.1,105.2 405.9,93.6 476.0,76.8 499.2,88.4" fill="#efe6dc" stroke="#46525e" strokeWidth="1.5" strokeLinejoin="round"/>
      <g {...part("flashing", "counter-flashing")}>
      <polyline points="405.9,213.3 429.1,256.6 499.2,239.8 476.0,196.4" fill="none" stroke="#b9c4cf" strokeWidth="9" strokeLinejoin="round" strokeLinecap="round"/>
      </g>
      <g {...part("chimney-cricket")}>
      <polyline points="405.9,213.3 401.8,102.6 476.0,196.4" fill="none" stroke="#b9c4cf" strokeWidth="8" strokeLinejoin="round" strokeLinecap="round"/></g>
      <polygon points="475.0,161.6 610.4,129.1 665.5,173.6 530.2,206.1" fill="#a7b3bf" stroke="#46525e" strokeWidth="1.6" strokeLinejoin="round"/>
      <polygon points="475.0,161.6 530.2,206.1 530.2,272.1 475.0,169.1" fill="#e8edf3" stroke="#46525e" strokeWidth="1.6" strokeLinejoin="round"/>
      <polygon points="530.2,206.1 665.5,173.6 665.5,239.7 530.2,272.1" fill="#ffffff" stroke="#46525e" strokeWidth="1.6" strokeLinejoin="round"/>
      <polygon points="556.7,221.5 638.9,201.8 638.9,245.3 556.7,265.0" fill="#cfe0ee" stroke="#46525e" strokeWidth="1.3" strokeLinejoin="round"/>
      <g {...part("step-flashing")}>
      <polyline points="475.0,169.1 530.2,272.1" fill="none" stroke="#b9c4cf" strokeWidth="9" strokeLinecap="round"/></g>
      <g {...part("apron-flashing")}>
      <polyline points="475.0,169.1 610.4,136.6" fill="none" stroke="#b9c4cf" strokeWidth="9" strokeLinecap="round"/></g>
      <g {...part("kickout-flashing")}>
      <circle cx="530.2" cy="272.1" r="17.4" fill="#b9c4cf" stroke="#46525e" strokeWidth="1.8"/></g>
      <g {...part("pipe-boots", "pipe-flashing")}>
      <polygon points="379.6,266.1 427.9,254.5 447.7,291.3 399.3,302.9" fill="#b9c4cf" stroke="#46525e" strokeWidth="1.5" strokeLinejoin="round"/>
      <ellipse cx="413.6" cy="278.7" rx="12.6" ry="5.8" fill="#5b6773" stroke="#46525e" strokeWidth="1.2"/>
      </g>
      <polygon points="405.9,280.6 421.4,276.8 421.4,235.7 405.9,239.5" fill="#12304d" stroke="#46525e" strokeWidth="1.3" strokeLinejoin="round"/>
      <ellipse cx="413.6" cy="237.6" rx="7.7" ry="3.4" fill="#2b4a68" stroke="#46525e" strokeWidth="1.1"/>
      <polygon points="713.4,267.9 852.6,337.6 852.6,516.4 713.4,446.8" fill="#e8edf3" stroke="#46525e" strokeWidth="1.6" strokeLinejoin="round"/>
      <polygon points="920.3,248.8 988.0,305.1 988.0,484.0 852.6,516.4 852.6,337.6" fill="#ffffff" stroke="#46525e" strokeWidth="1.6" strokeLinejoin="round"/>
      <polygon points="728.1,152.7 920.3,248.8 988.0,305.1 848.8,235.4" fill="#8d9aa8" stroke="#46525e" strokeWidth="1.7" strokeLinejoin="round"/>
      <polygon points="728.1,152.7 920.3,248.8 852.6,337.6 713.4,267.9" fill="#a7b3bf" stroke="#46525e" strokeWidth="1.7" strokeLinejoin="round"/>
      <polyline points="728.1,152.7 920.3,248.8" fill="none" stroke="#12304d" strokeWidth="8" strokeLinecap="round"/>
      <g {...part("ice-water-shield")}>
      <polygon points="707.8,157.6 748.4,147.8 733.7,263.1 693.1,272.8" fill="#12304d" stroke="#08203a" strokeWidth="1.4" strokeLinejoin="round"/>
      <polygon points="707.8,157.6 748.4,147.8 869.1,230.6 828.5,240.3" fill="#12304d" stroke="#08203a" strokeWidth="1.4" strokeLinejoin="round"/>
      </g>
      <g {...part("valley-flashing")}>
      <polyline points="728.1,152.7 713.4,267.9" fill="none" stroke="#b9c4cf" strokeWidth="9" strokeLinecap="round"/>
      <polyline points="728.1,152.7 848.8,235.4" fill="none" stroke="#b9c4cf" strokeWidth="9" strokeLinecap="round"/></g>
      <g {...part("starter-shingles")}>
      <polygon points="240.6,408.9 873.9,256.9 855.9,223.3 222.6,375.3" fill="#7d8b99" stroke="#46525e" strokeWidth="1.3" strokeLinejoin="round"/>
      <polygon points="146.3,232.7 240.6,408.9 270.5,401.8 176.3,225.5" fill="#7d8b99" stroke="#46525e" strokeWidth="1.3" strokeLinejoin="round"/>
      </g>
      <g {...part("drip-edge", "drip-edge-flashing")}>
      <polyline points="146.3,232.7 240.6,408.9 873.9,256.9" fill="none" stroke="#b9c4cf" strokeWidth="9" strokeLinejoin="round" strokeLinecap="round"/>
      <polyline points="146.3,232.7 240.6,408.9 873.9,256.9" fill="none" stroke="#46525e" strokeWidth="1.4" strokeLinejoin="round" strokeLinecap="round" opacity="0.5"/>
      </g>
      <g {...part("ridge-vent")}>
      <polygon points="192.2,221.7 733.7,91.8 733.7,61.8 192.2,191.7" fill="#6c7986" stroke="#46525e" strokeWidth="1.5" strokeLinejoin="round"/>
      <line x1="230.9" y1="212.4" x2="230.9" y2="182.5" stroke="#55626f" strokeWidth="1.1"/>
      <line x1="269.6" y1="203.2" x2="269.6" y2="173.2" stroke="#55626f" strokeWidth="1.1"/>
      <line x1="308.2" y1="193.9" x2="308.2" y2="163.9" stroke="#55626f" strokeWidth="1.1"/>
      <line x1="346.9" y1="184.6" x2="346.9" y2="154.6" stroke="#55626f" strokeWidth="1.1"/>
      <line x1="385.6" y1="175.3" x2="385.6" y2="145.3" stroke="#55626f" strokeWidth="1.1"/>
      <line x1="424.3" y1="166.0" x2="424.3" y2="136.0" stroke="#55626f" strokeWidth="1.1"/>
      <line x1="463.0" y1="156.7" x2="463.0" y2="126.8" stroke="#55626f" strokeWidth="1.1"/>
      <line x1="501.6" y1="147.5" x2="501.6" y2="117.5" stroke="#55626f" strokeWidth="1.1"/>
      <line x1="540.3" y1="138.2" x2="540.3" y2="108.2" stroke="#55626f" strokeWidth="1.1"/>
      <line x1="579.0" y1="128.9" x2="579.0" y2="98.9" stroke="#55626f" strokeWidth="1.1"/>
      <line x1="617.7" y1="119.6" x2="617.7" y2="89.6" stroke="#55626f" strokeWidth="1.1"/>
      <line x1="656.3" y1="110.3" x2="656.3" y2="80.4" stroke="#55626f" strokeWidth="1.1"/>
      <line x1="695.0" y1="101.0" x2="695.0" y2="71.1" stroke="#55626f" strokeWidth="1.1"/>
      </g>
      <g {...part("ridge-cap")}>
      <polyline points="146.3,232.7 192.2,191.7" fill="none" stroke="#12304d" strokeWidth="8" strokeLinecap="round"/>
      <polyline points="192.2,191.7 733.7,61.8" fill="none" stroke="#12304d" strokeWidth="8" strokeLinecap="round"/>
      <polyline points="733.7,61.8 779.6,80.7" fill="none" stroke="#12304d" strokeWidth="8" strokeLinecap="round"/>
      </g>
    </svg>
  );
}
